name: kony
description: "A new Flutter project."
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase and authentication
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # State management
  provider: ^6.0.5

  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  google_fonts: ^4.0.0
  animate_do: ^4.0.1
  rxdart: ^0.27.7

  flutter_pdfview: ^1.2.7
  path: ^1.8.3

  # PDF generation
  pdf: ^3.10.4
  printing: ^5.13.2
  path_provider: ^2.1.1

  # For opening files - using a different package that works better
  share_plus: ^7.0.0

  # Image handling (for future photo attachments)
  image_picker: ^1.0.4

  open_file: ^3.5.4
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Added for launcher icons
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ✅ Added assets path for app logo
  assets:
    - assets/icon/app_logo.png

# ✅ Configuration for app launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_logo.png"
