// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_i_snqrJHccBp2qpMLhFfhyRVwBoJ7z0',
    appId: '1:373594331946:web:20c17dfa80cdba1bcd9c53',
    messagingSenderId: '373594331946',
    projectId: 'kony-25092',
    authDomain: 'kony-25092.firebaseapp.com',
    storageBucket: 'kony-25092.firebasestorage.app',
    measurementId: 'G-QE6LX3NEDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC03OzcWVM4KeeWPxYwbPIHH0JYoY8PBD4',
    appId: '1:373594331946:android:daf0ce989dc74d53cd9c53',
    messagingSenderId: '373594331946',
    projectId: 'kony-25092',
    storageBucket: 'kony-25092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsKX1F41ymPVKxofaiV--OmzdN95pzJw',
    appId: '1:373594331946:ios:e7da2ec7c3f08ab9cd9c53',
    messagingSenderId: '373594331946',
    projectId: 'kony-25092',
    storageBucket: 'kony-25092.firebasestorage.app',
    iosBundleId: 'com.example.kony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsKX1F41ymPVKxofaiV--OmzdN95pzJw',
    appId: '1:373594331946:ios:e7da2ec7c3f08ab9cd9c53',
    messagingSenderId: '373594331946',
    projectId: 'kony-25092',
    storageBucket: 'kony-25092.firebasestorage.app',
    iosBundleId: 'com.example.kony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_i_snqrJHccBp2qpMLhFfhyRVwBoJ7z0',
    appId: '1:373594331946:web:64fbe9a8ef52cb25cd9c53',
    messagingSenderId: '373594331946',
    projectId: 'kony-25092',
    authDomain: 'kony-25092.firebaseapp.com',
    storageBucket: 'kony-25092.firebasestorage.app',
    measurementId: 'G-JEZP0VXGZ9',
  );
}
