@startuml
!define CLOUDORANGE
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


Person(technicien, "Technicien", "Utilisateur mobile")
Person(admin, "Administrateur", "Utilisateur web et mobile")

System_Boundary(c1, "Système Kony") {
    Container(mobile_app, "Application Mobile", "Flutter, Provider", "Permet aux techniciens et administrateurs de créer et gérer des rapports sur le terrain")
    Container(web_admin, "Interface d'Administration Web", "React, Material UI", "Permet aux administrateurs de gérer les utilisateurs et valider les rapports")
    
    ContainerDb(firebase, "Firebase", "Cloud Firestore, Auth, Storage, Functions", "Stockage des données, authentification et logique métier")
}

Rel(technicien, mobile_app, "Utilise")
Rel(admin, mobile_app, "Utilise")
Rel(admin, web_admin, "Utilise")
Rel(mobile_app, firebase, "Lit et écrit des données, synchronise")
Rel(web_admin, firebase, "Lit et écrit des données")

@enduml