@startuml
!define DEVOPS
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml


rectangle "Développement" {
  [Code Source] --> [Analyses Statiques]
  [Analyses Statiques] --> [Tests Unitaires]
}

rectangle "Intégration" {
  [Tests Unitaires] --> [Build]
  [Build] --> [Tests d'Intégration]
}

rectangle "Déploiement" {
  [Tests d'Intégration] --> [Déploiement Staging]
  [Déploiement Staging] --> [Tests Acceptance]
  [Tests Acceptance] --> [Déploiement Production]
}

@enduml